//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libCounchinn.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECCION
    {
        public int ID_DIRECCION { get; set; }
        public string CALLE { get; set; }
        public string ALTURA { get; set; }
        public string PISO { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string PAIS { get; set; }
        public string CUIDAD { get; set; }
        public string COD_POSTAL { get; set; }
        public Nullable<double> LATITUD { get; set; }
        public Nullable<double> LONGITUD { get; set; }
        public Nullable<bool> ESTADO_DIRECCION { get; set; }
    }
}
