//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libCounchinn.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ModeloLibCouchin : DbContext
    {
        public ModeloLibCouchin()
            : base("name=ModeloLibCouchin")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DIRECCION> DIRECCIONs { get; set; }
        public virtual DbSet<PERSONA> PERSONAs { get; set; }
        public virtual DbSet<PUBLICACION> PUBLICACIONs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TABLA> TABLAClaves { get; set; }
        public virtual DbSet<TABLAS> TABLASDescripciones { get; set; }
        public virtual DbSet<TIPO_HOSPEDAJE> TIPO_HOSPEDAJE { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
        public virtual DbSet<FOTO> FOTOS { get; set; }
        public virtual DbSet<CONTRIBUCIONE> CONTRIBUCIONES { get; set; }
        public virtual DbSet<COUCHINNS_REALIZADOS> COUCHINNS_REALIZADOS { get; set; }
        public virtual DbSet<RESERVA> RESERVAS { get; set; }
    
        public virtual ObjectResult<SEL_LOGIN_Result> SEL_LOGIN(string nOMBRE_USUARIO, string cONTRASEÑA)
        {
            var nOMBRE_USUARIOParameter = nOMBRE_USUARIO != null ?
                new ObjectParameter("NOMBRE_USUARIO", nOMBRE_USUARIO) :
                new ObjectParameter("NOMBRE_USUARIO", typeof(string));
    
            var cONTRASEÑAParameter = cONTRASEÑA != null ?
                new ObjectParameter("CONTRASEÑA", cONTRASEÑA) :
                new ObjectParameter("CONTRASEÑA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_LOGIN_Result>("SEL_LOGIN", nOMBRE_USUARIOParameter, cONTRASEÑAParameter);
        }
    
        public virtual int INS_CONTRIBUCIONES_USUARIO(Nullable<int> iD_USUARIO, string mONTO, Nullable<System.DateTime> fECHA)
        {
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            var mONTOParameter = mONTO != null ?
                new ObjectParameter("MONTO", mONTO) :
                new ObjectParameter("MONTO", typeof(string));
    
            var fECHAParameter = fECHA.HasValue ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INS_CONTRIBUCIONES_USUARIO", iD_USUARIOParameter, mONTOParameter, fECHAParameter);
        }
    
        public virtual int INS_TIPOHOSPEDAJE(string dESCRIPCION)
        {
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INS_TIPOHOSPEDAJE", dESCRIPCIONParameter);
        }
    
        public virtual ObjectResult<SEL_TIPOHOSPEDAJE_Result> SEL_TIPOHOSPEDAJE(Nullable<bool> pARAM)
        {
            var pARAMParameter = pARAM.HasValue ?
                new ObjectParameter("PARAM", pARAM) :
                new ObjectParameter("PARAM", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_TIPOHOSPEDAJE_Result>("SEL_TIPOHOSPEDAJE", pARAMParameter);
        }
    
        public virtual int UPD_ACTUALIZAR_CONTRASENA(Nullable<int> iD_USUARIO, string cONTRASEÑA)
        {
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            var cONTRASEÑAParameter = cONTRASEÑA != null ?
                new ObjectParameter("CONTRASEÑA", cONTRASEÑA) :
                new ObjectParameter("CONTRASEÑA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPD_ACTUALIZAR_CONTRASENA", iD_USUARIOParameter, cONTRASEÑAParameter);
        }
    
        public virtual int UPD_TIPO_HOSPEDAJE(Nullable<int> iD_TIPO_HOSPEDAJE, string dESCRIPCION, Nullable<bool> eSTADO)
        {
            var iD_TIPO_HOSPEDAJEParameter = iD_TIPO_HOSPEDAJE.HasValue ?
                new ObjectParameter("ID_TIPO_HOSPEDAJE", iD_TIPO_HOSPEDAJE) :
                new ObjectParameter("ID_TIPO_HOSPEDAJE", typeof(int));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var eSTADOParameter = eSTADO.HasValue ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPD_TIPO_HOSPEDAJE", iD_TIPO_HOSPEDAJEParameter, dESCRIPCIONParameter, eSTADOParameter);
        }
    
        public virtual ObjectResult<SEL_IMAGENESPUBLICACION_Result> SEL_IMAGENESPUBLICACION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_IMAGENESPUBLICACION_Result>("SEL_IMAGENESPUBLICACION");
        }
    
        public virtual ObjectResult<SEL_VERDETALLESHOSPEDAJE_Result> SEL_VERDETALLESHOSPEDAJE(Nullable<int> iD_PUBLICACION)
        {
            var iD_PUBLICACIONParameter = iD_PUBLICACION.HasValue ?
                new ObjectParameter("ID_PUBLICACION", iD_PUBLICACION) :
                new ObjectParameter("ID_PUBLICACION", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_VERDETALLESHOSPEDAJE_Result>("SEL_VERDETALLESHOSPEDAJE", iD_PUBLICACIONParameter);
        }
    
        public virtual int INS_IMAGEN_PUBLICACION(byte[] iMAGEN, Nullable<int> iD_PUB)
        {
            var iMAGENParameter = iMAGEN != null ?
                new ObjectParameter("IMAGEN", iMAGEN) :
                new ObjectParameter("IMAGEN", typeof(byte[]));
    
            var iD_PUBParameter = iD_PUB.HasValue ?
                new ObjectParameter("ID_PUB", iD_PUB) :
                new ObjectParameter("ID_PUB", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INS_IMAGEN_PUBLICACION", iMAGENParameter, iD_PUBParameter);
        }
    
        public virtual ObjectResult<SEL_ULTIMO_ID_PERSONA_Result> SEL_ULTIMO_ID_PERSONA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_ULTIMO_ID_PERSONA_Result>("SEL_ULTIMO_ID_PERSONA");
        }
    
        public virtual int INS_PERSONA(string nOMBRE, string aPELLIDO, string e_MAIL_LARGO)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDOParameter = aPELLIDO != null ?
                new ObjectParameter("APELLIDO", aPELLIDO) :
                new ObjectParameter("APELLIDO", typeof(string));
    
            var e_MAIL_LARGOParameter = e_MAIL_LARGO != null ?
                new ObjectParameter("E_MAIL_LARGO", e_MAIL_LARGO) :
                new ObjectParameter("E_MAIL_LARGO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INS_PERSONA", nOMBREParameter, aPELLIDOParameter, e_MAIL_LARGOParameter);
        }
    
        public virtual int INS_USUARIO(Nullable<int> iD_PERSONA, string nOMRE_USUARIO, string cONTRASEÑA, Nullable<int> tIPO_USUARIO)
        {
            var iD_PERSONAParameter = iD_PERSONA.HasValue ?
                new ObjectParameter("ID_PERSONA", iD_PERSONA) :
                new ObjectParameter("ID_PERSONA", typeof(int));
    
            var nOMRE_USUARIOParameter = nOMRE_USUARIO != null ?
                new ObjectParameter("NOMRE_USUARIO", nOMRE_USUARIO) :
                new ObjectParameter("NOMRE_USUARIO", typeof(string));
    
            var cONTRASEÑAParameter = cONTRASEÑA != null ?
                new ObjectParameter("CONTRASEÑA", cONTRASEÑA) :
                new ObjectParameter("CONTRASEÑA", typeof(string));
    
            var tIPO_USUARIOParameter = tIPO_USUARIO.HasValue ?
                new ObjectParameter("TIPO_USUARIO", tIPO_USUARIO) :
                new ObjectParameter("TIPO_USUARIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INS_USUARIO", iD_PERSONAParameter, nOMRE_USUARIOParameter, cONTRASEÑAParameter, tIPO_USUARIOParameter);
        }
    }
}
