//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libCounchinn.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        public int ID_PERSONA { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string E_MAIL { get; set; }
        public Nullable<int> UBICACION { get; set; }
        public Nullable<int> NACIONALIDAD { get; set; }
        public Nullable<int> IDIOMA { get; set; }
        public byte[] FOTO_PERFIL { get; set; }
        public string AUX1 { get; set; }
        public Nullable<bool> AUX2 { get; set; }
        public string E_MAIL_LARGO { get; set; }
    }
}
