//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libCounchinn.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLA
    {
        public int ID { get; set; }
        public string COD_TABLAS { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<bool> AUX1 { get; set; }
        public string AUX2 { get; set; }
    }
}
