//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libCouch2.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUBLICACION
    {
        public int ID_PUBLICACION { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_FIN { get; set; }
        public Nullable<int> TIPO_HOSPEDAJE { get; set; }
        public Nullable<int> CANT_PERSONAS { get; set; }
        public Nullable<bool> ESTADO_PUBLICACION { get; set; }
        public Nullable<int> FOTOS { get; set; }
        public string AUX1 { get; set; }
        public string AUX2 { get; set; }
    }
}
