//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libCouch2.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLA1
    {
        public int ID { get; set; }
        public string COD_TABLA { get; set; }
        public string CLAVE { get; set; }
        public string DESCRIPCION { get; set; }
        public string AUX1 { get; set; }
        public Nullable<bool> AUX2 { get; set; }
        public byte[] AUX3 { get; set; }
        public Nullable<int> AUX4 { get; set; }
    }
}
