//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libCouch2.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_HOSPEDAJE
    {
        public int ID_TIPO_HOSPEDAJE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<bool> ESTADO { get; set; }
        public string AUX1 { get; set; }
    }
}
