//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libCouch2.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int ID_USUARIO { get; set; }
        public Nullable<int> ID_PERSONA { get; set; }
        public string NOMRE_USUARIO { get; set; }
        public string CONTRASEÑA { get; set; }
        public Nullable<int> TIPO_USUARIO { get; set; }
        public Nullable<int> CALIFICACION { get; set; }
        public Nullable<bool> ESTADO_USUARIO { get; set; }
        public string AUX1 { get; set; }
    }
}
